##Titan analysis

library(TITAN2)
library(tidyverse)
library(viridisLite)
library(vegan)

phy.aoa.pruned <- readRDS("Phyloseq_AOA_Pruned.rds")
ASV.aoa.tbl <- readRDS("ASV_AOA_Table.rds")
TAX.all.aoa.tbl <- readRDS("TAX_ALL_AOA_Table.rds")

TAX10.aoa.tbl <- TAX.all.aoa.tbl %>% group_by(TAX10, STAND, PLOT) %>% summarize(COUNT = sum(COUNT))%>% ungroup()%>% select(TAX10, STAND, PLOT, COUNT)

TAX10.aoa.perc.tbl <- TAX10.aoa.tbl  %>% group_by(TAX10) %>% summarise(TAX10.COUNT = sum(COUNT)) %>% ungroup() %>% mutate(TOTAL.COUNT = sum(TAX10.COUNT)) %>% mutate(TAX10.PERC = 100 *(TAX10.COUNT/TOTAL.COUNT))%>% select(TAX10, TAX10.PERC)

TAX10.aoa.tmp.tbl <- TAX10.aoa.tbl  %>% group_by(TAX10) %>% mutate(TAX10.TOTAL = sum(COUNT))%>% ungroup() %>% filter(TAX10.TOTAL > 0) %>% group_by(PLOT) %>% mutate(PLOT.COUNT = sum(COUNT))%>% ungroup() %>% group_by(TAX10, PLOT) %>% mutate(PROP = sum(COUNT)/PLOT.COUNT) %>% ungroup() %>% mutate(HELLINGER = sqrt(PROP))

TAX10.aoa.trim.tbl <- TAX10.aoa.tbl %>% mutate(PA = ifelse(COUNT > 0,1,0))%>% group_by(TAX10) %>% inner_join(., TAX10.aoa.perc.tbl, by = "TAX10") %>% mutate(OCCURRENCE = sum(PA))%>% ungroup() %>% filter(TAX10.PERC >= 0.1 & OCCURRENCE >= 3)

TAX10.TAX2.aoa.tbl <- TAX.all.aoa.tbl %>% group_by(TAX10,TAX2, STAND, PLOT) %>% summarize(COUNT = sum(COUNT))%>% ungroup()%>% select(TAX10, TAX2, STAND, PLOT, COUNT)

TAX10.group.titan.aoa.tbl <- TAX10.TAX2.aoa.tbl %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NT-Alpha", "NT-Alpha", NA)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Gamma", "NS-Gamma", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Delta", "NS-Delta", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Beta", "NS-Beta", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Alpha", "NS-Alpha", TAX2.GROUP)) %>% select(TAX10, TAX2.GROUP) %>% distinct()

phy.aoa.samdata.df <- data.frame(sample_data(phy.aoa.pruned)) %>%  as_tibble(., rownames = "SAMPLE.ID")
env.nmin.df <- phy.aoa.samdata.df %>% select(PLOT, N.MIN) %>% arrange(PLOT) %>% column_to_rownames(var = "PLOT") %>% as.data.frame(.)
env.ph.df <- phy.aoa.samdata.df %>% select(PLOT, SOIL.PH) %>% arrange(PLOT) %>% column_to_rownames(var = "PLOT") %>% as.data.frame(.)
env.ammpost.df <- phy.aoa.samdata.df %>% select(PLOT, AMM.CORRECTED.POST) %>% arrange(PLOT) %>% column_to_rownames(var = "PLOT") %>% as.data.frame(.)

phy.aoa.hel <- decostand(phyloseq::otu_table(phy.aoa.pruned), method = "hellinger")

TAX10.aoa.trim.titan.in.df <- TAX10.aoa.trim.tbl %>% select(TAX10) %>% distinct() %>% inner_join(., TAX10.aoa.tmp.tbl, by = "TAX10") %>% select(PLOT, TAX10, HELLINGER) %>% pivot_wider(id_cols = PLOT, names_from = "TAX10", values_from = "HELLINGER") %>% arrange(PLOT) %>% column_to_rownames(var = "PLOT") %>% as.data.frame(.)

TAX10.aoa.trim.titan.nmin <- titan(env.nmin.df, TAX10.aoa.trim.titan.in.df, minSplt =5, numPerm = 1000, boot = TRUE, nBoot = 1000, imax = FALSE, ivTot = FALSE, pur.cut = 0.95, rel.cut = 0.95, ncpus =4, memory = FALSE)

TAX10.aoa.trim.titan.ph <- titan(env.ph.df, TAX10.aoa.trim.titan.in.df, minSplt =5, numPerm = 1000, boot = TRUE, nBoot = 1000, imax = FALSE, ivTot = FALSE, pur.cut = 0.95, rel.cut = 0.95, ncpus =4, memory = FALSE)

TAX10.aoa.trim.titan.ammpost <- titan(env.ammpost.df, TAX10.aoa.trim.titan.in.df, minSplt =5, numPerm = 1000, boot = TRUE, nBoot = 1000, imax = FALSE, ivTot = FALSE, pur.cut = 0.95, rel.cut = 0.95, ncpus =4, memory = FALSE)

TAX10.titan.response.aoa.nmin.tbl <- as_tibble(TAX10.aoa.trim.titan.nmin$sppmax, rownames = NA) %>% rownames_to_column(var = "TAX10") %>% select (TAX10, zenv.cp, '5%', '95%', z.median, filter, maxgrp) %>% rename(ZENV.CP = "zenv.cp", LCI = "5%", UCI = "95%", Z.MEDIAN = "z.median", GROUP = "filter", MAXGRP = "maxgrp") %>% mutate(Z.MEDIAN = ifelse(MAXGRP == 1, -1 * Z.MEDIAN, Z.MEDIAN)) %>% inner_join(.,TAX10.group.titan.tbl, by = "TAX10") %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% arrange(TAX2.GROUP.LABEL, Z.MEDIAN) %>% mutate(TAX10 = factor(TAX10, levels = TAX10)) %>% mutate(SIG = ifelse(GROUP >0, "Significant", "Not Significant")) %>% mutate(SIG = factor(SIG, levels = c("Significant", "Not Significant")))

TAX10.titan.response.aoa.ph.tbl <- as_tibble(TAX10.aoa.trim.titan.ph$sppmax, rownames = NA) %>% rownames_to_column(var = "TAX10") %>% select (TAX10, zenv.cp, '5%', '95%', z.median, filter, maxgrp) %>% rename(ZENV.CP = "zenv.cp", LCI = "5%", UCI = "95%", Z.MEDIAN = "z.median", GROUP = "filter", MAXGRP = "maxgrp") %>% mutate(Z.MEDIAN = ifelse(MAXGRP == 1, -1 * Z.MEDIAN, Z.MEDIAN)) %>% inner_join(.,TAX10.group.titan.tbl, by = "TAX10") %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% arrange(TAX2.GROUP.LABEL, Z.MEDIAN) %>% mutate(TAX10 = factor(TAX10, levels = TAX10)) %>% mutate(SIG = ifelse(GROUP >0, "Significant", "Not Significant")) %>% mutate(SIG = factor(SIG, levels = c("Significant", "Not Significant")))

TAX10.titan.response.aoa.ammpost.tbl <- as_tibble(TAX10.aoa.trim.titan.ammpost$sppmax, rownames = NA) %>% rownames_to_column(var = "TAX10") %>% select (TAX10, zenv.cp, '5%', '95%', z.median, filter, maxgrp) %>% rename(ZENV.CP = "zenv.cp", LCI = "5%", UCI = "95%", Z.MEDIAN = "z.median", GROUP = "filter", MAXGRP = "maxgrp") %>% mutate(Z.MEDIAN = ifelse(MAXGRP == 1, -1 * Z.MEDIAN, Z.MEDIAN)) %>% inner_join(.,TAX10.group.titan.tbl, by = "TAX10") %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% arrange(TAX2.GROUP.LABEL, Z.MEDIAN) %>% mutate(TAX10 = factor(TAX10, levels = TAX10)) %>% mutate(SIG = ifelse(GROUP >0, "Significant", "Not Significant")) %>% mutate(SIG = factor(SIG, levels = c("Significant", "Not Significant")))

TAX10.titan.response.aoa.nmin.plot <- ggplot()+geom_bar(data=TAX10.titan.response.aoa.nmin.tbl, aes(x=TAX10, y=Z.MEDIAN, fill = TAX2.GROUP.LABEL, alpha = SIG), stat = "identity", width = 0.75) + scale_fill_viridis_d(name = NULL, option = "plasma", begin =0.1, end = 0.9) + scale_alpha_manual(name = NULL, values = c(1, 0.3)) + geom_hline(yintercept = 0, linetype = 2, size = 0.5, colour = "black") + labs(x="ASV Taxon", y = "Median Z-score\n(response to inorganic N availabilty)") + coord_flip() + scale_x_discrete(limits=rev(levels(TAX10.titan.response.aoa.nmin.tbl$TAX10))) + theme(axis.line = element_line(colour = "black", size = 0.5), panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.5),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

TAX10.titan.response.aoa.ph.plot <- ggplot()+geom_bar(data=TAX10.titan.response.aoa.ph.tbl, aes(x=TAX10, y=Z.MEDIAN, fill = TAX2.GROUP.LABEL, alpha = SIG), stat = "identity", width = 0.75) + scale_fill_viridis_d(name = NULL, option = "plasma", begin =0.1, end = 0.9) + scale_alpha_manual(name = NULL, values = c(1, 0.3)) + geom_hline(yintercept = 0, linetype = 2, size = 0.5, colour = "black") + labs(x="ASV Taxon", y = "Median Z-score\n(response to inorganic N availabilty)") + coord_flip() + scale_x_discrete(limits=rev(levels(TAX10.titan.response.aoa.ph.tbl$TAX10))) + theme(axis.line = element_line(colour = "black", size = 0.5), panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.5),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

TAX10.titan.response.aoa.ammpost.plot <- ggplot()+geom_bar(data=TAX10.titan.response.aoa.ammpost.tbl, aes(x=TAX10, y=Z.MEDIAN, fill = TAX2.GROUP.LABEL, alpha = SIG), stat = "identity", width = 0.75) + scale_fill_viridis_d(name = NULL, option = "plasma", begin =0.1, end = 0.9) + scale_alpha_manual(name = NULL, values = c(1, 0.3)) + geom_hline(yintercept = 0, linetype = 2, size = 0.5, colour = "black") + labs(x="ASV Taxon", y = "Median Z-score\n(response to inorganic N availabilty)") + coord_flip() + scale_x_discrete(limits=rev(levels(TAX10.titan.response.aoa.ammpost.tbl$TAX10))) + theme(axis.line = element_line(colour = "black", size = 0.5), panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.5),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

TAX10.fig.input.aoa.nmin.tbl <- as_tibble(TAX10.aoa.trim.titan.nmin$sppmax, rownames = "TAX10") %>% inner_join(., TAX10.group.titan.aoa.tbl, by = "TAX10") %>% dplyr::rename(RESPONSE.GROUP = "filter")  %>% select(TAX10, TAX2.GROUP, RESPONSE.GROUP) %>% distinct()  %>% group_by(TAX2.GROUP)%>% summarise(POSITIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP == 2]), NEGATIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==1]), NO.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==0]), TOTAL.TAX10 = length(TAX2.GROUP)) %>% ungroup() %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% pivot_longer(cols=POSITIVE.RESPONSE : NEGATIVE.RESPONSE, names_to = "RESPONSE", values_to = "COUNT") %>% mutate(PROPORTION = COUNT/TOTAL.TAX10) %>% mutate(PROPORTION = ifelse(RESPONSE == "NEGATIVE.RESPONSE", -1 *PROPORTION, PROPORTION)) %>% mutate(SIG.LABEL = paste("(", COUNT, "/", TOTAL.TAX10, ")", sep="")) %>% mutate(LABEL.POSITION = ifelse(RESPONSE =="POSITIVE.RESPONSE", 0.2 + PROPORTION, PROPORTION - 0.2))

TAX10.fig.input.aoa.ph.tbl <- as_tibble(TAX10.aoa.trim.titan.ph$sppmax, rownames = "TAX10") %>% inner_join(., TAX10.group.titan.aoa.tbl, by = "TAX10") %>% dplyr::rename(RESPONSE.GROUP = "filter")  %>% select(TAX10, TAX2.GROUP, RESPONSE.GROUP) %>% distinct()  %>% group_by(TAX2.GROUP)%>% summarise(POSITIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP == 2]), NEGATIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==1]), NO.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==0]), TOTAL.TAX10 = length(TAX2.GROUP)) %>% ungroup() %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% pivot_longer(cols=POSITIVE.RESPONSE : NEGATIVE.RESPONSE, names_to = "RESPONSE", values_to = "COUNT") %>% mutate(PROPORTION = COUNT/TOTAL.TAX10) %>% mutate(PROPORTION = ifelse(RESPONSE == "NEGATIVE.RESPONSE", -1 *PROPORTION, PROPORTION)) %>% mutate(SIG.LABEL = paste("(", COUNT, "/", TOTAL.TAX10, ")", sep="")) %>% mutate(LABEL.POSITION = ifelse(RESPONSE =="POSITIVE.RESPONSE", 0.2 + PROPORTION, PROPORTION - 0.2))

TAX10.fig.input.aoa.ammpost.tbl <- as_tibble(TAX10.aoa.trim.titan.ammpost$sppmax, rownames = "TAX10") %>% inner_join(., TAX10.group.titan.aoa.tbl, by = "TAX10") %>% dplyr::rename(RESPONSE.GROUP = "filter")  %>% select(TAX10, TAX2.GROUP, RESPONSE.GROUP) %>% distinct()  %>% group_by(TAX2.GROUP)%>% summarise(POSITIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP == 2]), NEGATIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==1]), NO.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==0]), TOTAL.TAX10 = length(TAX2.GROUP)) %>% ungroup() %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% pivot_longer(cols=POSITIVE.RESPONSE : NEGATIVE.RESPONSE, names_to = "RESPONSE", values_to = "COUNT") %>% mutate(PROPORTION = COUNT/TOTAL.TAX10) %>% mutate(PROPORTION = ifelse(RESPONSE == "NEGATIVE.RESPONSE", -1 *PROPORTION, PROPORTION)) %>% mutate(SIG.LABEL = paste("(", COUNT, "/", TOTAL.TAX10, ")", sep="")) %>% mutate(LABEL.POSITION = ifelse(RESPONSE =="POSITIVE.RESPONSE", 0.2 + PROPORTION, PROPORTION - 0.2))

TAX10.titan.aoa.nmin.plot <- ggplot() +   geom_bar(data = TAX10.fig.input.aoa.nmin.tbl, aes(x = TAX2.GROUP.LABEL, y = PROPORTION, fill = RESPONSE),colour = NA, stat = "identity", alpha = 0.75) +   geom_hline(yintercept = 0,linetype = 2,size = 0.5,colour = "black") + geom_text(data = TAX10.fig.input.aoa.nmin.tbl, aes(x = TAX2.GROUP.LABEL, y = LABEL.POSITION, colour = RESPONSE), label = TAX10.fig.input.aoa.nmin.tbl$SIG.LABEL, size = 2.5) + scale_colour_viridis_d(name = "Association with\ninorganic N", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma", guide = FALSE) + scale_fill_viridis_d(name = "Association with\ninorgaic N", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma") +   scale_y_continuous(limits = c(-1.2, 1.2), expand = expansion(mult = c(0.1, 0.1)), breaks = c(-1, -0.5, 0, 0.5, 1),labels = c("1.0", "0.5", "0", "0.5", "1.0")) + coord_flip() + scale_x_discrete(limits = rev(levels(TAX10.fig.input.aoa.nmin.tbl$TAX2.GROUP.LABEL))) + labs(x = NULL, y = "Proportion of ASV in Clade") + theme(axis.line = element_line(colour = "black", size = 0.5),panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.35),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

ggsave("Titan_Nmin_AOA.pdf", width=8.5, height=10)

TAX10.titan.aoa.ph.plot <- ggplot() +   geom_bar(data = TAX10.fig.input.aoa.ph.tbl, aes(x = TAX2.GROUP.LABEL, y = PROPORTION, fill = RESPONSE),colour = NA, stat = "identity", alpha = 0.75) +   geom_hline(yintercept = 0,linetype = 2,size = 0.5,colour = "black") + geom_text(data = TAX10.fig.input.aoa.ph.tbl, aes(x = TAX2.GROUP.LABEL, y = LABEL.POSITION, colour = RESPONSE), label = TAX10.fig.input.aoa.ph.tbl$SIG.LABEL, size = 2.5) + scale_colour_viridis_d(name = "Association with\nSoil pH", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma", guide = FALSE) + scale_fill_viridis_d(name = "Association with\nSoil pH", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma") +   scale_y_continuous(limits = c(-1.2, 1.2), expand = expansion(mult = c(0.1, 0.1)), breaks = c(-1, -0.5, 0, 0.5, 1),labels = c("1.0", "0.5", "0", "0.5", "1.0")) + coord_flip() + scale_x_discrete(limits = rev(levels(TAX10.fig.input.aoa.ph.tbl$TAX2.GROUP.LABEL))) + labs(x = NULL, y = "Proportion of ASV in Clade") + theme(axis.line = element_line(colour = "black", size = 0.5),panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.35),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

ggsave("Titan_Soil_pH_AOA.pdf", width=8.5, height=10)

TAX10.titan.aoa.ammpost.plot <- ggplot() +   geom_bar(data = TAX10.fig.input.aoa.ammpost.tbl, aes(x = TAX2.GROUP.LABEL, y = PROPORTION, fill = RESPONSE),colour = NA, stat = "identity", alpha = 0.75) +   geom_hline(yintercept = 0,linetype = 2,size = 0.5,colour = "black") + geom_text(data = TAX10.fig.input.aoa.ammpost.tbl, aes(x = TAX2.GROUP.LABEL, y = LABEL.POSITION, colour = RESPONSE), label = TAX10.fig.input.aoa.ammpost.tbl$SIG.LABEL, size = 2.5) + scale_colour_viridis_d(name = "Association with\nAmmonium Post Incubation", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma", guide = FALSE) + scale_fill_viridis_d(name = "Association with\nAmmonium Post Incubation", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma") +   scale_y_continuous(limits = c(-1.2, 1.2), expand = expansion(mult = c(0.1, 0.1)), breaks = c(-1, -0.5, 0, 0.5, 1),labels = c("1.0", "0.5", "0", "0.5", "1.0")) + coord_flip() + scale_x_discrete(limits = rev(levels(TAX10.fig.input.aoa.ammpost.tbl$TAX2.GROUP.LABEL))) + labs(x = NULL, y = "Proportion of ASV in Clade") + theme(axis.line = element_line(colour = "black", size = 0.5),panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.35),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

ggsave("Titan_Amm_Post_AOA.pdf", width=8.5, height=10)

