##Titan analysis

library(titan2)
library(tidyverse)

ps.ASV.tbl <- as.data.frame(otu_table(phy.aoa.min2)) %>% as_tibble(., rownames="SAMPLE.ID")
ps.samp.tbl2 <- as.data.frame(sample_data(phy.aoa.min2B)) %>% as_tibble(., rownames = "SAMPLE.ID")

#Redid the table making for titan up to TAX10.all.trim.tbl and that table had 950 entries for both the multisamp and the way we did stuff before. That should mean that the same ASVs were kicked out before this step no matter which input it started the process with, thought he percentages are slightly different (since they had different number of reads total).

Titan

TAX10.all.trim.titan.aoa.in.df <- TAX10.all.trim.aoa.tbl %>% select(TAX10) %>% distinct() %>% inner_join(., TAX10.all.tmp.aoa.tbl, by = "TAX10") %>% select(PLOT, TAX10, HELLINGER) %>% pivot_wider(id_cols = PLOT, names_from = "TAX10", values_from = "HELLINGER") %>% arrange(PLOT) %>% column_to_rownames(var = "PLOT") %>% as.data.frame(.)

TAX10.TAX2.all.aoa.tbl <- ASV.all.aoa.tbl %>% inner_join(ps.tax.aoa.tbl, ., by = "ASV") %>% group_by(TAX10,TAX2, STAND, PLOT) %>% summarize(COUNT = sum(COUNT))%>% ungroup()%>% select(TAX10, TAX2, STAND, PLOT, COUNT)

TAX10.group.titan.tbl <- TAX10.TAX2.all.aoa.tbl %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NT-Alpha", "NT-Alpha", NA)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Gamma", "NS-Gamma", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Delta", "NS-Delta", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Beta", "NS-Beta", TAX2.GROUP)) %>% mutate(TAX2.GROUP = ifelse(TAX2 == "NS-Alpha", "NS-Alpha", TAX2.GROUP)) %>% select(TAX10, TAX2.GROUP) %>% distinct()

TAX10.titan.response.tbl <- as_tibble(TAX10.all.trim.aoa.titan$sppmax, rownames = NA) %>% rownames_to_column(var = "TAX10") %>% select (TAX10, zenv.cp, '5%', '95%', z.median, filter, maxgrp) %>% rename(ZENV.CP = "zenv.cp", LCI = "5%", UCI = "95%", Z.MEDIAN = "z.median", GROUP = "filter", MAXGRP = "maxgrp") %>% mutate(Z.MEDIAN = ifelse(MAXGRP == 1, -1 * Z.MEDIAN, Z.MEDIAN)) %>% inner_join(.,TAX10.group.titan.tbl, by = "TAX10") %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% arrange(TAX2.GROUP.LABEL, Z.MEDIAN) %>% mutate(TAX10 = factor(TAX10, levels = TAX10)) %>% mutate(SIG = ifelse(GROUP >0, "Significant", "Not Significant")) %>% mutate(SIG = factor(SIG, levels = c("Significant", "Not Significant")))

TAX10.titan.response.plot <- ggplot()+geom_bar(data=TAX10.titan.response.tbl, aes(x=TAX10, y=Z.MEDIAN, fill = TAX2.GROUP.LABEL, alpha = SIG), stat = "identity", width = 0.75) + scale_fill_viridis_d(name = NULL, option = "plasma", begin =0.1, end = 0.9) + scale_alpha_manual(name = NULL, values = c(1, 0.3)) + geom_hline(yintercept = 0, linetype = 2, size = 0.5, colour = "black") + labs(x="ASV Taxon", y = "Median Z-score\n(response to inorganic N availabilty)") + coord_flip() + scale_x_discrete(limits=rev(levels(TAX10.titan.response.tbl$TAX10))) + theme(axis.line = element_line(colour = "black", size = 0.5), panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.5),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())

TAX10.fig.input.tbl <- as_tibble(TAX10.all.trim.aoa.titan$sppmax, rownames = "TAX10") %>% inner_join(., TAX10.group.titan.tbl, by = "TAX10") %>% dplyr::rename(RESPONSE.GROUP = "filter")  %>% select(TAX10, TAX2.GROUP, RESPONSE.GROUP) %>% distinct()  %>% group_by(TAX2.GROUP)%>% summarise(POSITIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP == 2]), NEGATIVE.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==1]), NO.RESPONSE = length(TAX2.GROUP[RESPONSE.GROUP ==0]), TOTAL.TAX10 = length(TAX2.GROUP)) %>% ungroup() %>% mutate(TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NT-Alpha", "NT-Alpha", NA), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Gamma", "NS-Gamma", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Delta", "NS-Delta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Beta", "NS-Beta", TAX2.GROUP.LABEL), TAX2.GROUP.LABEL = ifelse(TAX2.GROUP == "NS-Alpha", "NS-Alpha", TAX2.GROUP.LABEL)) %>% mutate(TAX2.GROUP.LABEL = factor(TAX2.GROUP.LABEL, levels = c("NT-Alpha", "NS-Gamma", "NS-Delta", "NS-Beta", "NS-Alpha"))) %>% pivot_longer(cols=POSITIVE.RESPONSE : NEGATIVE.RESPONSE, names_to = "RESPONSE", values_to = "COUNT") %>% mutate(PROPORTION = COUNT/TOTAL.TAX10) %>% mutate(PROPORTION = ifelse(RESPONSE == "NEGATIVE.RESPONSE", -1 *PROPORTION, PROPORTION)) %>% mutate(SIG.LABEL = paste("(", COUNT, "/", TOTAL.TAX10, ")", sep="")) %>% mutate(LABEL.POSITION = ifelse(RESPONSE =="POSITIVE.RESPONSE", 0.2 + PROPORTION, PROPORTION - 0.2))

library(viridisLite)

TAX10.titan.plot <- ggplot() +   geom_bar(data = TAX10.fig.input.tbl, aes(x = TAX2.GROUP.LABEL, y = PROPORTION, fill = RESPONSE),colour = NA, stat = "identity", alpha = 0.75) +   geom_hline(yintercept = 0,linetype = 2,size = 0.5,colour = "black") + geom_text(data = TAX10.fig.input.tbl, aes(x = TAX2.GROUP.LABEL, y = LABEL.POSITION, colour = RESPONSE), label = TAX10.fig.input.tbl$SIG.LABEL, size = 2.5) + scale_colour_viridis_d(name = "Association with\ninorganic N", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma", guide = FALSE) + scale_fill_viridis_d(name = "Association with\ninorgaic N", labels = c("Negative", "Positive"), begin = 0.2, end = 0.8, option = "plasma") +   scale_y_continuous(limits = c(-1.2, 1.2), expand = expansion(mult = c(0.1, 0.1)), breaks = c(-1, -0.5, 0, 0.5, 1),labels = c("1.0", "0.5", "0", "0.5", "1.0")) + coord_flip() + scale_x_discrete(limits = rev(levels(TAX10.fig.input.tbl$TAX2.GROUP.LABEL))) + labs(x = NULL, y = "Proportion of ASV in Clade") + theme(axis.line = element_line(colour = "black", size = 0.5),panel.background = element_rect(fill = NA), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), plot.title = element_text(size = 12, colour = "black", hjust = -0.35),axis.title.x = element_text(size = 7, colour = "black"), axis.title.y = element_text(size = 7, colour = "black"), axis.text.x = element_text(size = 6, colour = "black"), axis.text.y = element_text(size = 6, colour = "black"), legend.title = element_text(size = 7, colour = "black"), legend.text = element_text(size = 6, colour = "black"), legend.key = element_blank())
